# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip', models.GenericIPAddressField()),
                ('score', models.PositiveSmallIntegerField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_ratings', to='star_ratings.Rating')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='anonymousrating',
            unique_together=set([('ip', 'rating')]),
        ),
    ]
