# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
    ]
