# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
